### ISSUE TITLE
Bundle is incompatible with Symfony 4 Flex

### ISSUE THREAD

**Issue by sushrest** [codereviewvideos/fos-rest-and-user-bundle-integration#4]
Bundle is incompatible with Symfony 4 Flex

**Comment by codereviewvideos** [comment]
Hi @sushrest 

Which bundle are you referring too? 

Thanks,

Chris

**Comment by codereviewvideos** [comment]
closing as this tutorial is not for Symfony 4, and I have received no response on which bundle you are referring too. Please reopen if needed.
